wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1713668141.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.3
      5: 0.16.6
      8:
      - 2
      - 5
      13: linux-x86_64
